name: myapp
description: "Aaroha - Internship Management Platform"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.2.1
  go_router: ^17.1.0
  tuple: ^2.0.2
  supabase_flutter: ^2.12.2
  intl: ^0.20.2
  mailer: ^6.1.0
  http: ^1.2.2
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.2
  url_launcher: ^6.3.1
  file_picker: ^11.0.2
  file_selector: ^1.1.0
  excel: ^4.0.6
  share_plus: ^12.0.2
  google_fonts: ^6.2.1
  onesignal_flutter: 5.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
