// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl072Zcl7uoXxh8hpYV-I3AU8ca5IWQLA',
    appId: '1:671445371808:web:a0bcc3a45fd31fbe91b2c5',
    messagingSenderId: '671445371808',
    projectId: 'internship-project-4b55d',
    authDomain: 'internship-project-4b55d.firebaseapp.com',
    storageBucket: 'internship-project-4b55d.firebasestorage.app',
    measurementId: 'G-47YB0GX3KW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUqohMVULKcwDk0UHVEvLTqIjZR9QDqaM',
    appId: '1:671445371808:android:f36cb7cb2a1b61a991b2c5',
    messagingSenderId: '671445371808',
    projectId: 'internship-project-4b55d',
    storageBucket: 'internship-project-4b55d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAObfrjIvAUsbPeme4uoOzvx3f25jde7xw',
    appId: '1:671445371808:ios:f9598f787501966d91b2c5',
    messagingSenderId: '671445371808',
    projectId: 'internship-project-4b55d',
    storageBucket: 'internship-project-4b55d.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAObfrjIvAUsbPeme4uoOzvx3f25jde7xw',
    appId: '1:671445371808:ios:f9598f787501966d91b2c5',
    messagingSenderId: '671445371808',
    projectId: 'internship-project-4b55d',
    storageBucket: 'internship-project-4b55d.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAl072Zcl7uoXxh8hpYV-I3AU8ca5IWQLA',
    appId: '1:671445371808:web:48520650205522b891b2c5',
    messagingSenderId: '671445371808',
    projectId: 'internship-project-4b55d',
    authDomain: 'internship-project-4b55d.firebaseapp.com',
    storageBucket: 'internship-project-4b55d.firebasestorage.app',
    measurementId: 'G-KB0RD3NDHX',
  );
}
