// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4vSzlus2IKiZCETtioVwNOv9LErw2Td0',
    appId: '1:238760860837:web:4ba5dd024e5311bd0a814c',
    messagingSenderId: '238760860837',
    projectId: 'aaroha-af3cb',
    authDomain: 'aaroha-af3cb.firebaseapp.com',
    storageBucket: 'aaroha-af3cb.firebasestorage.app',
    measurementId: 'G-DZVDG3XG2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxJAzt9P43-pqp8EUw_eRosd86zhPwR7E',
    appId: '1:238760860837:android:4b75188f978901b20a814c',
    messagingSenderId: '238760860837',
    projectId: 'aaroha-af3cb',
    storageBucket: 'aaroha-af3cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbsGHrJumMCqWgGCm2jG1RK6zX_Do4v1s',
    appId: '1:238760860837:ios:29bafdcb0a83a0300a814c',
    messagingSenderId: '238760860837',
    projectId: 'aaroha-af3cb',
    storageBucket: 'aaroha-af3cb.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbsGHrJumMCqWgGCm2jG1RK6zX_Do4v1s',
    appId: '1:238760860837:ios:29bafdcb0a83a0300a814c',
    messagingSenderId: '238760860837',
    projectId: 'aaroha-af3cb',
    storageBucket: 'aaroha-af3cb.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4vSzlus2IKiZCETtioVwNOv9LErw2Td0',
    appId: '1:238760860837:web:97c15e85e45459160a814c',
    messagingSenderId: '238760860837',
    projectId: 'aaroha-af3cb',
    authDomain: 'aaroha-af3cb.firebaseapp.com',
    storageBucket: 'aaroha-af3cb.firebasestorage.app',
    measurementId: 'G-CQ7C16QQ1N',
  );
}
